# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.6.2"
  rdflib_min: "7.1.4"
  protobuf_min: "6.30.0"
  # TODO: remove if/when oldest supported is available
  protobuf_check_min: "6.31.1"

package:
  name: pyjelly
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyjelly/pyjelly-${{ version }}.tar.gz
  sha256: ad7254cc2f0b9d3b9a18059d7096669d86f9510f7bf658f0011ca1ea43bc5f7f

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - protobuf >=${{ protobuf_min }}
    - python >=${{ python_min }}
    - typing_extensions >=4.12.2
  run_constraints:
    - rdflib >=${{ rdflib_min }}

tests:
  - python:
      imports: pyjelly
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - tests/
        - pyproject.toml
    requirements:
      run:
        - coverage
        - hypothesis
        - inline-snapshot
        - pip
        - protobuf ${{ protobuf_check_min }}.*
        - pytest
        - pytest-mock
        - pytest-subtests
        - python ${{ python_min }}.*
        - rdflib ${{ rdflib_min }}.*
    script:
      - pip check
      - coverage run --source=pyjelly --branch -m pytest -vv --tb=long --color=yes -k "not test_parse_serialize"
      - coverage report --show-missing --skip-covered --fail-under=87

about:
  homepage: https://github.com/Jelly-RDF/pyjelly
  summary: Jelly-RDF implementation for Python
  license: Apache-2.0
  license_file:
    - LICENSE
    - submodules/protobuf/LICENSE
  documentation:  https://jelly-rdf.github.io/pyjelly

extra:
  recipe-maintainers:
    - bollwyvl
