# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.7.0"
  rdflib_min: "7.1.4"
  protobuf_min: "6.30.0"
  # TODO: remove if/when oldest supported is available
  protobuf_check_min: "6.31.1"

package:
  name: pyjelly
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyjelly/pyjelly-${{ version }}.tar.gz
  sha256: adf65e58b81531277edb972ffea17146ef146c24517a22f594d30f9dd9cd6eb6

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
  host:
    - hatch-mypyc
    - hatchling >=1.24
    - mypy >=1.8
    - pip
    - python
  run:
    - protobuf >=${{ protobuf_min }}
    - python >=${{ python_min }}
    - typing_extensions >=4.12.2
    - mypy-extensions>=1.0.0
  run_constraints:
    - rdflib >=${{ rdflib_min }}

tests:
  - python:
      imports: pyjelly
      pip_check: true
  - files:
      source:
        - tests/
        - pyproject.toml
    requirements:
      run:
        - coverage
        - hypothesis
        - inline-snapshot
        - pip
        - protobuf ${{ protobuf_check_min }}.*
        - pytest >=8.3.4,<8.5.0
        - pytest-mock
        - pytest-subtests
        - rdflib ${{ rdflib_min }}.*
    script:
      - pip check
      - coverage run --source=pyjelly --branch -m pytest -vv --tb=long --color=yes -k "not test_parse_serialize"
      - coverage report --show-missing --skip-covered --fail-under=87

about:
  homepage: https://github.com/Jelly-RDF/pyjelly
  summary: Jelly-RDF implementation for Python
  license: Apache-2.0
  license_file:
    - LICENSE
    - submodules/protobuf/LICENSE
  documentation: https://jelly-rdf.github.io/pyjelly

extra:
  recipe-maintainers:
    - bollwyvl
